#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features       = 'cxx cxxprogram',
    includes       = ['.', '../../../src/modipulate'],
    source         = bld.path.ant_glob(['**/*.c', '**/*.cpp']),
    target         = 'console',
    use            = 'portaudio modipulate'
)
