#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.shlib(
        features  = 'cxx cshlib',
        includes  = ['.', 'libmodplug-hacked'],
        source    = bld.path.ant_glob(['**/*.c', '**/*.cpp']),
        target    = 'modipulate',
        use       = 'portaudio'
    )
