#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.stlib(
        includes  = ['.', 'libmodplug-hacked'],
        source    = bld.path.ant_glob(['**/*.c', '**/*.cpp']),
        target    = 'modipulate',
        name      = 'modipulate-static',
        use       = 'portaudio'
    )
    
    bld.shlib(
        includes  = ['.', 'libmodplug-hacked'],
        source    = bld.path.ant_glob(['**/*.c', '**/*.cpp']),
        target    = 'modipulate',
        use       = 'portaudio'
    )
